{ inputs, lib, ... }:
let
  secretsFile = ../../secrets/secrets.yaml;
  secretsFileExists = builtins.pathExists secretsFile;
in
{
  imports = [ inputs.sops-nix.nixosModules.sops ];

  # Fail early with a clear message instead of building a system nobody can log into.
  assertions = [
    {
      assertion = secretsFileExists;
      message = "secrets/secrets.yaml is missing (or not tracked by git). Create it with sops: see docs/INSTALL.md, section 'Secrets bootstrap'.";
    }
  ];

  sops = lib.mkIf secretsFileExists {
    defaultSopsFile = secretsFile;
    defaultSopsFormat = "yaml";
    age = {
      # sshd is disabled, so NixOS does not create this key: it is generated by hand
      # during installation (see docs/INSTALL.md) and converted to an age key here.
      sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
      generateKey = false;
    };
    # Hash of the user's password, decrypted before the accounts are created.
    secrets."user-password".neededForUsers = true;
  };
}
